import fs from 'fs';
import path from 'path';
import { ToolManifest } from '../../shared/types';
import { config } from '../config';
import { toolRegistry } from './ToolRegistry';

/**
 * Scans the tools directory for manifest.json files and registers found tools.
 */
export class Scanner {
  /**
   * Scan the tools directory and register all found tools.
   * Returns a summary of what was found.
   */
  scan(): { found: number; registered: number; updated: number; errors: string[] } {
    const toolsDir = config.toolsDir;
    fs.mkdirSync(toolsDir, { recursive: true });

    const entries = fs.readdirSync(toolsDir, { withFileTypes: true });
    const errors: string[] = [];
    let registered = 0;
    let updated = 0;

    for (const entry of entries) {
      if (!entry.isDirectory() || entry.name.startsWith('.')) continue;

      const toolDir = path.join(toolsDir, entry.name);
      const manifestPath = path.join(toolDir, 'manifest.json');

      if (!fs.existsSync(manifestPath)) continue;

      try {
        const manifestRaw = fs.readFileSync(manifestPath, 'utf-8');
        const manifest = JSON.parse(manifestRaw) as ToolManifest;

        // Validate required fields
        if (!manifest.id || !manifest.name || !manifest.mode || !manifest.runtime) {
          errors.push(`${entry.name}: Missing required fields (id, name, mode, runtime)`);
          continue;
        }

        // Check if already registered
        const existing = toolRegistry.get(manifest.id);
        if (existing) {
          toolRegistry.register(manifest, toolDir);
          updated++;
        } else {
          toolRegistry.register(manifest, toolDir);
          registered++;
        }
      } catch (err: unknown) {
        const message = err instanceof Error ? err.message : String(err);
        errors.push(`${entry.name}: ${message}`);
      }
    }

    return {
      found: registered + updated,
      registered,
      updated,
      errors,
    };
  }

  /**
   * Create a new tool directory with a manifest
   */
  createTool(manifest: ToolManifest, files?: { name: string; content: string }[]): string {
    const toolDir = path.join(config.toolsDir, manifest.id);
    fs.mkdirSync(toolDir, { recursive: true });

    // Write manifest
    fs.writeFileSync(
      path.join(toolDir, 'manifest.json'),
      JSON.stringify(manifest, null, 2),
      'utf-8'
    );

    // Write additional files (scripts, etc.)
    if (files) {
      for (const file of files) {
        fs.writeFileSync(path.join(toolDir, file.name), file.content, 'utf-8');
      }
    }

    return toolDir;
  }

  /**
   * Generate a README stub for a tool
   */
  generateReadme(manifest: ToolManifest): string {
    const lines = [
      `# ${manifest.name}`,
      '',
      `> v${manifest.version} | ${manifest.mode} | ${manifest.category || 'uncategorized'}`,
      '',
      manifest.description,
      '',
      '## Usage',
      '',
      `**Mode:** \`${manifest.mode}\``,
      `**Runtime:** \`${manifest.runtime.type}\``,
      `**Entry:** \`${manifest.runtime.entry}\``,
      '',
      '## Inputs',
      '',
      ...manifest.inputs.map(
        (i) => `- **${i.label}** (\`${i.key}\`): ${i.type}${i.required ? ' *required*' : ''} — ${i.help || ''}`
      ),
      '',
      '## Outputs',
      '',
      ...manifest.outputs.map((o) => `- **${o.label}**: ${o.type}${o.mime ? ` (${o.mime})` : ''}`),
      '',
      '## Adapter',
      '',
      `- Input format: \`${manifest.adapter.input.format}\``,
      `- Output format: \`${manifest.adapter.output.format}\``,
      '',
      `> Generated by GadgetServer on ${new Date().toISOString()}`,
    ];

    return lines.join('\n');
  }
}

export const scanner = new Scanner();
